apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: kindforge-cl01-full-backup
  namespace: velero
spec:
  schedule: '@every 1h'
  template:
    includedNamespaces:
    - "*"
    excludedNamespaces:
    - minio
    ttl: 720h0m0s
