apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-v2
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: migrated
